spring.datasource.url=jdbc:mysql://localhost:3306/faculdade_api
spring.datasource.username=root
spring.datasource.password=Delta@4205*
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
